# Generated by Django 4.0.4 on 2022-05-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('num_dist', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descuento_choice', models.CharField(choices=[('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40')], default='20', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tel_casa', models.CharField(max_length=10)),
                ('tel_cel', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('centro_alta', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_ultima_compra', models.DateField()),
                ('meses_sin_compra', models.IntegerField()),
                ('fecha_alta', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('total_puntos', models.IntegerField()),
                ('campania', models.ManyToManyField(to='campanias.campania')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroExitoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('Exitoso', 'Cambio de residencia ( permanente o temporal)'), ('Exitoso', 'Es para su consumo personal'), ('Exitoso', 'Falta de recursos economicos'), ('Exitoso', 'Falta de tiempo'), ('Exitoso', 'Informativa'), ('Exitoso', 'Motivos de salud'), ('Exitoso', 'No compra con su codigo'), ('Exitoso', 'No conoce formas de compra'), ('Exitoso', 'Otros')], default=' ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroNoExitoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('No Exitoso', 'Linea fuera de servicio'), ('No Exitoso', 'No contesta'), ('No Exitoso', 'No le interesa se le brinde información'), ('No Exitoso', 'No se puede contactar por el horario'), ('No Exitoso', 'Numero del patrocinador'), ('No Exitoso', 'Telefono equivocado')], default=' ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('remarcar', models.BooleanField()),
                ('ultima_interaccion', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanias.contacto')),
                ('registro_exi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanias.registroexitoso')),
                ('registro_no_exi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanias.registronoexitoso')),
            ],
        ),
        migrations.CreateModel(
            name='Cedi',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanias.pais')),
            ],
        ),
        migrations.AddField(
            model_name='campania',
            name='cedis',
            field=models.ManyToManyField(to='campanias.cedi'),
        ),
    ]
