# Generated by Django 4.0.4 on 2022-06-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='campania',
            field=models.CharField(max_length=200, verbose_name='campaña'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='fecha_interaccion',
            field=models.DateTimeField(auto_now=True, verbose_name='última interacción'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='num_dist',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='número de empresario'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='registro_exi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='exitoso'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='registro_no_exi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='no exitoso'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tel_casa',
            field=models.CharField(max_length=10, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tel_cel',
            field=models.CharField(max_length=10, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='campania',
            name='nombre',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='campaña'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='num_dist',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de empresario'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tel_casa',
            field=models.CharField(max_length=10, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tel_cel',
            field=models.CharField(max_length=10, verbose_name='ceclular'),
        ),
    ]
