# Generated by Django 4.0.4 on 2022-06-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0003_alter_resultado_remarcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='registro_exi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='registro_no_exi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
