# Generated by Django 4.0.4 on 2022-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0004_alter_backup_comentario_alter_backup_registro_exi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='pais',
            field=models.CharField(max_length=100),
        ),
    ]
